### ISSUE TITLE
Bluecat Gateway running in Docker Container should log to STDOUT and STDERR

### ISSUE THREAD

**Issue by sanbornick** [bluecatlabs/gateway-workflows#110]
In most kubernetes distributions aggregate logging systems collect from STDOUT and STDERR only. Local logging is discouraged as well. Ephemeral disk local logging can lead to disk pressure events that causes the pods to be evicted. Mounted volume logging still requires other work including a separate process to ship those logs from a volume to the logging system of choice and logrotate that volume so it does not fill up.

Therefor, to make the gateway k8s friendly please log to STDOUT and STDERR only by default.

**Comment by chrisjws** [comment]
We are reviewing this internally. We may have some follow-up questions for you.

**Comment by michaelrn** [comment]
Closing this old issue as this has been resolved in Gateway.
Gateway can now be configured to log to STDOUT:
https://docs.bluecatnetworks.com/r/Gateway-Administration-Guide/Configuring-log-settings/22.4.1
