### ISSUE TITLE
Do no see existing worklows in the GUI

### ISSUE THREAD

**Issue by praemy65** [bluecatlabs/gateway-workflows#53]
Hello, 

Looking at /portal/bluecat_portal/workflows i can see different directory containing Workflow.
The only one showing up in the GUI is the /host_records
All others are not visible.
drwxr-xrwx 4 flask flask  59 Aug 27 09:09 dns/
drwxr-xrwx 6  6487 users 160 Aug 27 09:10 host_record/
drwxr-xr-x 4 flask flask  57 Sep  3 14:45 test/
drwxr-xrwx 7 flask flask 178 Aug 27 08:04 update_host_record_example/

the difference is the owner: flask:flask instaed of 6487:users.
I can not change the owner. 
Any idea to correct the issue?

Thanks
Pascal

**Comment by billfmorton** [comment]
Hey Pascal,

Are the workflow permissions set in the GUI after importing? (admin > workflow permissions)

Another thing to check:

To allow BlueCat Gateway to read and write workflows and configuration from the mapped bluecat_gateway folder, the folder must have read, write, and execute permissions for other users who are not in the folder’s group. Ensure the BlueCat Gateway container is running and execute the following

**command**:
chmod -R o=rwx <mapped bluecat gateway folder>
