### ISSUE TITLE
How to populate a TableField with data from MongoDB?

### ISSUE THREAD

**Issue by mrnorr** [bluecatlabs/gateway-workflows#55]
If I am to use PyMongo for instance to pull information from a Mongo database, how do I then populate a TableField on a workflow page?

**Comment by chrisjws** [comment]
Mongo data comes in dictionary form, from there if we have say some host information we'd setup like following:

First a form element in your _form.py:

`server_table = TableField(
        workflow_name=workflow_name,
        permissions=workflow_permission,
        label='',
        data_function=get_table_data,
        table_features={
            'searching': True,
            'paging': True,
            'ordering': True,
            'info': True
        },
        inputs={'ip4_network': 'ip4_network'}
)`

This will send the input ip4_network to the endpoint  get_table_data. Define get_table_data to return a dictionary with the element data:

`
# leaving out the lookup, I assume you know how to do this in Mongo. That will return a dictionary that we will reference below as records

my_table_data = {
        "columns": [
            {"title": "IP Address"},
            {'title': 'State'},
            {'title': 'Absolute Name'},
            {'title': 'Host Name'},
            {'title': 'PTR Record'},
        ],
        "data": [

        ]
    }
# in data dict above we add rows from mongo to map to the column values
# ex:
for record in records:
   my_table_data['data'].append([record['address'], record['addstate'], record['absname'], record['dnsname'], record['reverse']])

result = {}
result['status'] = 'SUCCESS'
result['data'] = {"table_field": my_table_data}

return jsonify(table_data)`

**Comment by chrisjws** [comment]
Mongo data comes in dictionary form, from there if we have say some host information we'd setup like following:

First a form element in your _form.py:

`server_table = TableField(
        workflow_name=workflow_name,
        permissions=workflow_permission,
        label='',
        data_function=get_table_data,
        table_features={
            'searching': True,
            'paging': True,
            'ordering': True,
            'info': True
        },
        inputs={'ip4_network': 'ip4_network'}
)`

This will send the input ip4_network to the endpoint  get_table_data. Define get_table_data to return a dictionary with the element data:


leaving out the lookup, I assume you know how to do this in Mongo. That will return a dictionary that we will reference below as records
`
my_table_data = {
        "columns": [
            {"title": "IP Address"},
            {'title': 'State'},
            {'title': 'Absolute Name'},
            {'title': 'Host Name'},
            {'title': 'PTR Record'},
        ],
        "data": [

        ]
    }

for record in records:
   my_table_data['data'].append([record['address'], record['addstate'], record['absname'], record['dnsname'], record['reverse']])

result = {}
result['status'] = 'SUCCESS'
result['data'] = {"table_field": my_table_data}

return jsonify(table_data)`

**Comment by mrnorr** [comment]
@chrisjws Thank you very much for your answer. Your code is extremely close to what I was trying but yours seems to handle the response parsing into the table data without error.

At the current moment I've setup the TableField on my form. and the table_data inside a get function, within a component_logic.py file, similar to how the UI Components example handles defining the tables. Everything appears to be in order expect for an attempt to set the table default?

Error as such:
`  File "C:\Users\$USER\Desktop\portal\bluecat\wtform_fields\table_field.py", line 35, in __init__
    self.table_data = data_function(default_val=True)
TypeError: __call__() got an unexpected keyword argument 'default_val'`


Workflow structure as such:

record_approvals_form.py
`"""
Table component form
"""
from bluecat.wtform_extensions import GatewayForm
from bluecat.wtform_fields import TableField

from .component_logic import get_record_approvals_table

import pymongo



class GenericFormTemplate(GatewayForm):
    """ Form template to generate html and javascript for page
    """
    workflow_name = 'record_approvals'
    workflow_permission = 'record_approvals_page'

    connection = pymongo.MongoClient('mongodb://localhost:27017/')
    db = connection.bluecat_portal_DB
    collection = connection.test
    userPin = "myusername"
    entities = db.collection.find({"user": userPin})

    server_table = TableField(
        workflow_name=workflow_name,
        permissions=workflow_permission,
        label='',
        data_function=get_record_approvals_table(entities),
        table_features={
            'searching': True,
            'paging': True,
            'ordering': True,
            'info': True
        },
        inputs={'entities': 'entities'}
    )
`

record_approvals_page.py
`"""
Table component page
"""
# Various Flask framework items.
import os

from flask import render_template, g, jsonify

from bluecat import route
from bluecat import util

import config.default_config as config
from .record_approvals_form import GenericFormTemplate
from main_app import app

import pymongo


def module_path():
    """
    Get module path.

    :return:
    """
    return os.path.dirname(os.path.abspath(str(__file__)))

# The workflow name must be the first part of any endpoints defined in this file.
# If you break this rule, you will trip up on other people's endpoint names and
# chaos will ensue.
@route(app, '/record_approvals/record_approvals_endpoint')
@util.workflow_permission_required('record_approvals_page')
@util.exception_catcher

def record_approvals_record_approvals_page():
    """
    Renders the form the user would first see when selecting the workflow.

    :return:
    """
    form = GenericFormTemplate()
    return render_template(
        'record_approvals_page.html',
        form=form,
        text=util.get_text(module_path(), config.language),
        options=g.user.get_options(),
    )`

component_logic.py
`"""
Component logic
"""

from flask import jsonify

from main_app import app

def get_record_approvals_table(entities):
    with app.app_context():
        record_approvals_table = {
            "columns": [
                {"title": "Request ID"},
                {'title': 'User'},
                {'title': 'Raw Request'},
                {'title': 'Approval Status'},
            ],
            "data": [

            ]
        }

        for e in entities:
            record_approvals_table['data'].append(
                [str(e['_id']), e['user'], e['hostname'], e['action']])

        result = {}
        result['status'] = 'SUCCESS'
        result['data'] = {"table_field": record_approvals_table}

        return jsonify(record_approvals_table)
`

**Comment by mrnorr** [comment]
Looks like I was able to self resolve it. I can't quite pin down what change exactly fixed it, but it boiled down to `jsonify()` was trying to encode(?) data that was already in JSON format? Removing it from the return ended up being the last piece before it stopped erroring. Here is the code as it stands if you're curious. Thank you again for pointing me in the right direction!

record_approvals_form.py

```
from bluecat.wtform_extensions import GatewayForm
from bluecat.wtform_fields import TableField

from .component_logic import get_record_approvals_table

class GenericFormTemplate(GatewayForm):
    """ Form template to generate html and javascript for page
    """
    workflow_name = 'record_approvals'
    workflow_permission = 'record_approvals_page'

    server_table = TableField(
        workflow_name=workflow_name,
        permissions=workflow_permission,
        label='',
        is_disabled_on_start=True,
        is_disabled_on_error=False,
        data_function=get_record_approvals_table,
        table_features={
            'searching': True,
            'paging': True,
            'ordering': True,
            'info': True
        },
    )
```

record_approvals_page.py

```
import os

from flask import render_template, g

from bluecat import route
from bluecat import util

import config.default_config as config
from .record_approvals_form import GenericFormTemplate
from main_app import app

def module_path():
    """
    Get module path.

    :return:
    """
    return os.path.dirname(os.path.abspath(str(__file__)))

# The workflow name must be the first part of any endpoints defined in this file.
# If you break this rule, you will trip up on other people's endpoint names and
# chaos will ensue.
@route(app, '/record_approvals/record_approvals_endpoint')
@util.workflow_permission_required('record_approvals_page')
@util.exception_catcher

def record_approvals_record_approvals_page():
    """
    Renders the form the user would first see when selecting the workflow.

    :return:
    """
    form = GenericFormTemplate()
    return render_template(
        'record_approvals_page.html',
        form=form,
        text=util.get_text(module_path(), config.language),
        options=g.user.get_options(),
    )
```

component_logic.py

```
import pymongo
from flask import g

def get_record_approvals_table(default_val=False):
    connection = pymongo.MongoClient('mongodb://localhost:27017/')
    db = connection.bluecat_portal_DB
    collection = connection.test
    userPin = g.user.get_username()
    entities = db.collection.find({"user": userPin})

    record_approvals_table = {
        "columns": [
            {"title": "Request ID"},
            {'title': 'User'},
            {'title': 'Raw Request'},
            {'title': 'Approval Status'},
        ],
        "data": [

        ]
    }

    for e in entities:
        record_approvals_table['data'].append(
            [str(e['_id']), str(e['user']), str(e['hostname']), str(e['action'])])

    result = {}
    result['status'] = 'SUCCESS'
    result['data'] = {"table_field": record_approvals_table}

    return record_approvals_table
```

**Comment by chrisjws** [comment]
Glad you were able to get it working!
