### ISSUE TITLE
Adding a button to each row in a WTForm's TableField?

### ISSUE THREAD

**Issue by mrnorr** [bluecatlabs/gateway-workflows#56]
How would you render in either a checkbox or text button inside, or next to, each row?

User | Host | Action | Approval
-- | -- | -- | --
myusername | host.domain.com | delete | []

EDIT:
The closest I can find in existing source code would be the checkbox inputs appended to the return in the following:
Certified/cisco_aci_example/cisco_aci_example_page.py

The output I end up getting is just the HTML text without rendering

User | Host | Action | Approval
-- | -- | -- | --
myusername | host.domain.com | delete | <input type="checkbox" id="{name}" name="{name}" {option} checked>

**Comment by mrnorr** [comment]
It appears the answer was in (as expected, a very similar workflow)
Community/Service Requests/manage_service_requests/manage_service_requests_form.py

In the $workflow_form.py you need to specifically indicate which column needs an additional render function done on it (best way I can describe it to myself)

```
class GenericFormTemplate(GatewayForm):
    """ Form template to generate html and javascript for page
    """
    workflow_name = 'record_approvals'
    workflow_permission = 'record_approvals_page'

    approvals_table = TableField(
        workflow_name=workflow_name,
        permissions=workflow_permission,
        label='',
        data_function=get_record_approvals_table,
        table_features={
            'searching': False,
            'paging': False,
            'ordering': False,
            'info': False,
            'lengthChange': True,
            'columnDefs': [
                {
                    'targets': [3],
                    'render': ''
                }],
        },
```

**Comment by chrisjws** [comment]
Glad you were able to find the answer, I was working on putting together an example but looks like you got it.

**Comment by mrnorr** [comment]
The thought is very much appreciated @chrisjws 
It was a lucky find 😄
