### ISSUE TITLE
How to populate a read only string field with a specified value on a Gateway UI form?

### ISSUE THREAD

**Issue by mrnorr** [bluecatlabs/gateway-workflows#57]
If I wanted to add a read-only pre-populated form field on an existing workflow form, what form field and parameters would I use? The closest that I can think would accomplish this would be something along the following:

```
username = CustomStringField(
    label='Username: ',
    readonly=True,
    value='myusername'
)
```

**Comment by billfmorton** [comment]
Try adding the default like below. 

default_group = CustomStringField(
        label='Default GitLab Group',
        default=gitlab_import_config.default_group, <-- this is the vaule
        is_disabled_on_start=True, <-- I never enable it in the form
        is_disabled_on_error=True,
        required=True
    )

You could also set it in the page: form.default_group.data = gitlab_import_config.default_group

**Comment by mrnorr** [comment]
Hey thanks Bill, that looks to be just what I was trying to accomplish!
