### ISSUE TITLE
How to default and lock in the 'Configuration' and 'View' in the UI Example workflows?

### ISSUE THREAD

**Issue by mrnorr** [bluecatlabs/gateway-workflows#58]
For instance:
Examples > Host Record > Add Host Record Example

The options presented to the end-user are:

- Configuration
- View
- Zone
- IP Address
- Hostname

How would you set the Configuration and View to specific choices and not allow the user to change them? Or for that matter, remove them entirely from the form, yet keeping those choices active on the back end?

**Comment by chrisjws** [comment]
You can make the default value like so:

 form.configuration.data = 100880

Then disable with Javascript. 

If your plan is to make it not optional for any user at any point, then I suggest removing the form field and only having the value set on the server side as your default.

**Comment by mrnorr** [comment]
Update:
It looks like I can at least limit what is chosen, however it still requires 'clicking' an option

If I add into the endpoint function on the 'page.py' just before returning the HTML render data~
```
    form.configuration.choices = [('1', 'Please Select'), (100001, 'internal-config')]
    form.view.choices = [('1', 'Please Select'), ('internal-view', 'internal-view')]
```

**Comment by mrnorr** [comment]
Update:
It loos like I found the fix to the whole 'clicking' portion, it appears you need to actually trigger a form 'process' function(?). Such as `form.process()`. This will then trigger whatever the subsequent form fields need for populating data, such as zone choice. See below for full workflow function.

```
@route(app, '/add_host_record_example/add_host_record_example_endpoint')
@util.workflow_permission_required('add_host_record_example_page')
@util.exception_catcher
def add_host_record_example_add_host_record_example_page():
    """
    Renders the form the user would first see when selecting the workflow.

    :return:
    """
    form = GenericFormTemplate()
    form.configuration.choices = [('1', 'Please Select'), (100001, 'internal-config')]
    form.configuration.default = 100001
    form.view.choices = [('1', 'Please Select'), ('internal-view', 'internal-view')]
    form.view.default = 'internal-view'
    form.process()
    return render_template(
        'add_host_record_example_page.html',
        form=form,
        text=util.get_text(module_path(), config.language),
        options=g.user.get_options()
    )
```

**Comment by mrnorr** [comment]
Final(?) Update:
Like you mentioned Chris, I was able to 'hide' them with JS 😃 

```
$("#configuration").hide();
$('label[for="configuration"]').hide();

$("#view").hide();
$('label[for="view"]').hide();
```
