### ISSUE TITLE
How to limit, or customize, what 'zones' can be chosen in the Host Record workflows?

### ISSUE THREAD

**Issue by mrnorr** [bluecatlabs/gateway-workflows#59]
By default it appears the Host Record workflows will pull down all possible zones based on your configuration and view, but if I were to want to present only certain zones, or customize the drop down list to my own choices, how would I accomplish this?

**Comment by billfmorton** [comment]
You could do it in the form and hard code the valid values like:

    workflow_name = 'get_audit_info'
    workflow_permission = 'get_audit_info_page'
    interval = CustomSelectField(
        workflow_name=workflow_name,
        permissions=workflow_permission,
        label='Time Interval',
        **choices=[('Please Select', 'Please Select'), ('1 hours', '1 hours'), ('2 hours', '2 hours'), ('5 hours', '5 hours'), ('12 hours', '12 hours'), ('24 hours', '24 hours')],**
        required=True,
        enable_on_complete=['search'],
        is_disabled_on_start=False
    )

Then in you pages, you would need to get the entity using seachByName and Zone.

Or you could create a function that only gets the specific zones you want. 

If you want to limit, you can use getZonesByHint. I think by default there's only 10 returned. I personally like this. It's an autocomplete for VV. For an example, look at the get_audit_logs workflow in the community. This isn't published yet, but will be later this week.

**Comment by mrnorr** [comment]
Thank you @billfmorton 

I ended up making a separate "filter" function as I didn't want to change the form field away from "Zone" to something like "CustomSelectField" as I wasn't sure how it was connecting to the other fields, which I now retrospectively see would have worked just as well.

```
def filter_zones(res):
    """
    Filter zones.

    :param res:
    :return:
    """
    try:
        res['data']['autocomplete_field'] = ['domainiwant.com']
        res['data']['select_field'] = [{'id': 123456, 'txt': 'domainiwant.com'}]
        return res
    except (TypeError, KeyError):
        return res
```

```
    zone = Zone(
        workflow_name=workflow_name,
        permissions=workflow_permission,
        label='Zone',
        required=True,
        clear_below_on_change=False,
        result_decorator=filter_zones,
        is_disabled_on_start=False,
        enable_dependencies={'on_complete': ['ip4_address']},
        disable_dependencies={'on_change': ['ip4_address']},
        clear_dependencies={'on_change': ['ip4_address', 'hostname']},
        should_cascade_disable_on_change=True,
        should_cascade_clear_on_change=True,
    )
```
