### ISSUE TITLE
How to rename a workflow?

### ISSUE THREAD

**Issue by mrnorr** [bluecatlabs/gateway-workflows#61]
For instance: The example workflow "Add Host Record Example". What would the easiest way to rename the entire workflow and all it's references to just "Add Host Record"?

**Comment by billfmorton** [comment]
You can rename the workflow title in the __init__.py

sub_pages = [
    {
        'name'        : 'vro_configuration_page',
        **'title'       : u'vRO Configuration',**
        'endpoint'    : 'vro_configuration/vro_configuration_endpoint',
        'description' : u'vro_configuration'
    },
]

To rename the endpoints and all references is a little more complicated. I recommend creating a new workflow with the naming you'd like, and then copy the core code from the example to the new workflow.
