### ISSUE TITLE
When adding a new host record, how do you check if the IP is already in use?

### ISSUE THREAD

**Issue by mrnorr** [bluecatlabs/gateway-workflows#62]
In my specific case, I have attempted to implement a check via `get_linked_entities` on the `ip4_address` object, however it seems to always return API exceptions saying the IP can't be found. However, when removing this check it will allow the record to be added no problem. Is there something obvious I'm missing, an existing function that I could import perhaps?

```
            configuration = g.user.get_api().get_entity_by_id(form.configuration.data)
            view = configuration.get_view(request.form['view'])

            absolute_name = form.hostname.data + '.' + request.form['zone']

            ip4_address = request.form['ip4_address']
            ip4_address_string = str(ip4_address)
            ip4_address_list.append(ip4_address)

            for ip in ip4_address_list:
                ip4_object = configuration.get_ip4_address(ip.strip())
                linked_entities = ip4_object.get_linked_entities('HostRecord')
                if len(list(linked_entities)) != 0:
                    raise ValueError("Has linked records")

            # Add host Record
            host_record = view.add_host_record(absolute_name, ip4_address_list)
```

**Comment by mrnorr** [comment]
This seems to work fine, I think the real issue is that it does not work for `UNALLOCATED `IP addresses

```
            ip_address = g.user.get_api().get_configuration(config.default_configuration).get_ip4_address(ip4_address)
            hosts = ip_address.get_linked_entities('HostRecord')
            if len(list(hosts)) != 0:
                raise ValueError("Has linked records")
```

**Comment by mrnorr** [comment]
Workaround that's been found for `UNALLOCATED` IP addresses would be a try/except as such:

```
#Check for any linked entities
for ip in ip4_address_list:
    try:
        ip_address = g.user.get_api().get_configuration(config.default_configuration).get_ip4_address(ip)
        hosts = ip_address.get_linked_entities('HostRecord')
        if len(list(hosts)) != 0:
            raise ValueError("This IP address is already in use, please use a different IP address.")
    except PortalException:
        pass
```

**Comment by christophermmeyer** [comment]
My suggestion was going to be the try/except. I would also specifically check for the error message instead of just catching and passing. The exception might be something different and you may want to handle it differently.

One suggestion for that loop would be to get the configuration before you enter the loop. As you have it there you will be making two API calls everything time(get_configuration and get_ip4_address) when you really only need to make one. Just save the configuration off before the loop and use it multiple times.
