### ISSUE TITLE
Medium Risk Vulnerability - Web Application Potentially Vulnerable to Clickjacking

### ISSUE THREAD

**Issue by mrnorr** [bluecatlabs/gateway-workflows#71]
Vulnerability: Tenable Nessus detects the default login page for BlueCat Gateway as vulnerable to click-jacking.
https://www.tenable.com/plugins/nessus/85582

Fix: Return the X-Frame-Options or Content-Security-Policy (with the 'frame-ancestors' directive) HTTP header with the page's response. This prevents the page's content from being rendered by another site when using the frame or iframe HTML tags.
https://flask.palletsprojects.com/en/master/security/

**Comment by chrisjws** [comment]
Thanks for letting us know. Our dev is looking into this.

**Comment by delmeherbert** [comment]
@mrnorr Thank you for bringing this to our attention. A fix for this vulnerability will be in the next release of BlueCat Gateway shipping early 2020.

**Comment by delmeherbert** [comment]
@mrnorr This fix is included in BlueCat Gateway 20.1.1 which is available today.
