### ISSUE TITLE
Potential Bug? POST /admin/api/workspace/import

### ISSUE THREAD

**Issue by mrnorr** [bluecatlabs/gateway-workflows#92]
It appears that when attempting to load the GitHub workflows via API by sending a POST /admin/api/workspace/import request to a Gateway 20.1.1 server with a proper JSON body with parameters (as per the documentation and release notes) it only ever responds with a '403 Forbidden' response.

**Comment by chrisjws** [comment]
Were you able to run UI import with the same user? Generally, 403 means that you are authenticated but lack permissions for the given workflow.

**Comment by mrnorr** [comment]
Hey Chris, yes I was able to do so.
I just gave it a new try to confirm that and it appears to potentially have been a caching issue with the Insomnia REST client, and wasn't forcing my second accounts new auth token value.

I apologise, user error, thank you for reply regardless!
