### ISSUE TITLE
Bluecat workflow add_host_record

### ISSUE THREAD

**Issue by D1eg0JB** [bluecatlabs/gateway-workflows#95]
Hello community:

I have dowloaded some of the workflows in here. I dont have so much experience on this but i feel that i have done great advances on it.

My issue: i have downloaded a workflow and uploaded to my environment. good.
But i have used the option "workflow_categories.txt" to mantain an order on my workflows.
The thing is that i have modified the __init_py file in one of the workflows and use a workflow_categories called: MANAGEMENT.
The folder is there but in the modification of __init_py i have changed the "title" and the "endpoint" and even when i deleted the folder MANAGEMENT and upload a correct __init_py file with the correct info, the system detects that __init_py is going to be used as the modified version ( not the correct one).

How can i make to "restart" flask or something to update the correct values?

Regards.

**Comment by christophermmeyer** [comment]
Good morning.

How are you making changes? The workflow_categories.txt only comes into play when you are using the built in export/import workflow. If you're just modifying the file and expecting it to change then it will no do that.

The best way to restart is to just issue the "docker restart <Gateway_Container_Name>". That will restart all services on the Gateway.

**Comment by tintomko** [comment]
Hello D1eg0JB,

File `workflow_categories.txt` is used during the import and export of a workflow. It is not intended for configuration of an already existing (imported) workflow.

"restart" of Flask is not provided. May I kindly ask that you restart the container and report back on whether you observe the desired behaviour/values?

**Comment by D1eg0JB** [comment]
I get it guys. my mistake was to modify __init_py file instead of create a workflow_categories.txt.
Now, for some reason if i want to include the workflow again in that folder the original modified file (__init_py) says go and look for the app on add_host_record/examples endpoint which not exists obviously. i want to know if deleting all content in folder and restarting the image is going to work. Or a workaround was to create all my workflows in that folder in another brand new folder.

**Comment by D1eg0JB** [comment]
Hey guys. I have another concern. Is there a possiblity to add some alias record and in the workflow page include a "tick" to search for external records? or create an alias to another subdomain, instead of the domain which belongs the alias?

Regards, Diego

**Comment by chrisjws** [comment]
Hi Diego, sorry I didn't realize this got dropped.

A quick look at it the code the line of interest is [here](https://github.com/bluecatlabs/gateway-workflows/blob/master/Certified/Alias%20Record/add_alias_record/add_alias_record_page.py#L84) 

You can feed that a string of an external host or conventional host within the same view. However, your issue will be from the form because if the zone in externalhost.example.com (in this case example.com) does not exist, it will disallow submission. You could either modify to allow a search, or change the input to a free form text box.
