### ISSUE TITLE
v20.1.1 Medium Vulnerability: Web Application Potentially Vulnerable to Clickjacking

### ISSUE THREAD

**Issue by ghost** [bluecatlabs/gateway-workflows#96]
Further actions needed to resolve a vulnerability. Same as Issue #71 
Latest version seen on: BlueCat Gateway 20.1.1

Medium Vulnerability: Web Application Potentially Vulnerable to Clickjacking

https://www.tenable.com/plugins/nessus/85582
https://cwe.mitre.org/data/definitions/693

The following pages do not use a click-jacking mitigation response header and contain a clickable event:
/css
/icons
/img
/static
/static/css

Fix: Return the X-Frame-Options or Content-Security-Policy (with the 'frame-ancestors' directive) HTTP header with the page's response. This prevents the page's content from being rendered by another site when using the frame or iframe HTML tags.

**Comment by chrisjws** [comment]
We have this issue in our Jira, will update once we have a release decided.

**Comment by dqeautomation** [comment]
Howdy BlueCat Labs Team,

Are you able to tell me who subscribed to this email report?

Many Thx,

Don


Don Wood  <><
NOC Technician II
Help Desk: 877.263.8638
dwood@dqe.com<mailto:dwood@dqe.com>

[signature_249306543]

**Comment by chrisjws** [comment]
This is addressed in Gateway 20.6.1. There is a potentially breaking change if you are using Gateway in an iframe.
