### ISSUE TITLE
Request: example for uploading response policy items RESTapi

### ISSUE THREAD

**Issue by TonyCrespoMe** [bluecatlabs/gateway-workflows#97]
It would be great to view an example on how to add a domain to a response policy (i.e. redirect) through the RESTapi. 

I have been attempting to use the function "....../REST/v1/uploadResponsePolicyItems?" without success, failing at "Error 415 Unsupported Media Type" . 

Would it be possible for you guys to assist.

**Comment by chrisjws** [comment]
Quick example, I can expand more on how this works if you need:

`            encoded_blacklist=io.StringIO(blacklist)
            g.user.get_api()._api_client.service.uploadResponsePolicyItems(policy_id, encoded_blacklist)
`

**Comment by haiders5** [comment]
Here is another example using our wrapped APIs:


                api = g.user.get_api()                                                     # get api object
                response_policy_id = 100001                                       # response policy id
                policy = api.get_entity_by_id(response_policy_id)
                policy.upload_response_policy_item('/path_tofile/file')

**Comment by TonyCrespoMe** [comment]
Sorry, but what type of file and format is expected for this POST?

**Comment by TonyCrespoMe** [comment]
> Here is another example using our wrapped APIs:
> 
> ```
>             # get api object 
>             api = g.user.get_api()                                             
>             # response policy id
>             response_policy_id = 100001                               
>             policy = api.get_entity_by_id(response_policy_id)
>             policy.upload_response_policy_item('/path_tofile/file')
> ```

Thanks for the example, would you mind giving an example of the file type and format required to be uploaded. 

I believe here is where i am having trouble and getting the 415 error following the api guide. 

Upload Response Policy Item
Uploads one response policy file containing a list of fully qualified domain names (FQDNs).

Output / Response
None.

API Call:
void uploadResponsePolicyItems( long parentId, byte[] policyItemsData )

Parameter            Description
parentId               The object ID of the parent response policy under which the 
                             response policyitem file is being uploaded.

policyItemsData The file to be uploaded under the response policy. This file is passed 
                           toAddress Manager as a byte array.Note:  This actual file size
                           should be no more than 75 MB

**Comment by TonyCrespoMe** [comment]
Thanks for the examples, would you mind giving an example of the file type and format/structure required to be uploaded.

I believe here is where i am having trouble and getting the "Error 415 Unsupported Media Type" following the api guide.

Upload Response Policy Item
Uploads one response policy file containing a list of fully qualified domain names (FQDNs).

Output / Response
None.

API Call:
void uploadResponsePolicyItems( long parentId, byte[] policyItemsData )

Parameter Description
parentId The object ID of the parent response policy under which the
response policyitem file is being uploaded.

policyItemsData The file to be uploaded under the response policy. This file is passed
toAddress Manager as a byte array.Note: This actual file size
should be no more than 75 MB

**Comment by chrisjws** [comment]
Hi Tony,

In the use case I have above, my blacklist is just a string variable that looks like this:

`domain1.com
domain1.net
domain2.com
domain2.net
`

**Comment by TonyCrespoMe** [comment]
> Hi Tony,
> 
> In the use case I have above, my blacklist is just a string variable that looks like this:
> 
> ```
> domain1.com
> domain1.net
> domain2.com
> domain2.net
> ```

Thank you very much for your help. 

I will be  closing this issue for now just not not have it hanging and will be giving it a try today.

**Comment by TonyCrespoMe** [comment]
> Here is another example using our wrapped APIs:
> 
> ```
>             # get api object 
>             api = g.user.get_api()                                             
>             # response policy id
>             response_policy_id = 100001                               
>             policy = api.get_entity_by_id(response_policy_id)
>             policy.upload_response_policy_item('/path_tofile/file')
> ```

Hi, 

Could you provide me with info about this wrapper api, specially where i can get it. 

Thank you!

**Comment by TonyCrespoMe** [comment]
@chrisjws Thanks for the help. 

I was unable to use this call using REST api but it worked on first try with SOAP. 

Question: Would you have in hand a process to get all items in a response policy? 
 i.e. "Response policy" being a "redirect", under the policy, i see more than 2k entries and would like to be able to download them through the api if possible. 

What i have tried is searchResponsePolicyItems() and it runs successfully, however, as per the call:
searchResponsePolicyItems(keyword, scope, start, count, properties)

For keyword, i am not able to use the "id" of the redirect policy but can use "Redirect" and it gives results for matching records. The issue that i have found is that there are 2 redirect policies hence i a get a combination of both and with a limit if i am not mistaken of 1k results.

Thanks for the help.
